class MainWindow {

	+ ontologyAdded : Signal
	+ ontologyRemoved : Signal
	+ updateRequested : Signal
	- widgets : Widget[]

	# synchronize()
	# _showOptionDialog_()
	# _addWidget_(widgetType : String, widgetMenu : QMenu)
	+ createPySumoWidget(widgetType : String, widgetMenu : QMenu)
	+ addDeleteWidgetAction(widget : PySUMOWidget)
	+ addOrRestoreWidget(widget : PySUMOWidget, menu : QMenu, directAdd : Boolean)
	+ closeEvent(event : QEvent)
	+ createStatusBar()
	+ setupStatusConnection()
	+ displayLog(socket)
	# _updateStatusbar_(wrappedWidget : Widget)
	# _deleteWidget_(widget : PySUMOWidget)
	+ connectWidget(widget : PySUMOWidget)
	+ disconnectWidget(widget : PySUMOWidget, callback)
	+ getDefaultOutputPath()
	# _newOntology_()
	# _openLocalOntology_()
	# _openRemoteOntology_()
	+ addOntology(ontology : Ontology, newversion : String)
	+ notifyOntologyAdded(ontology : Ontology)
	# _ClearRecentOntologiesHistory_()
	# _deleteOntology_(ontology : Ontology, ontologyMenu : QMenu)
	# _updateOntology_(ontology : Ontology)
	# _revertOntology_(ontology : Ontology, ontologyMenu : QMenu)
	# _showOntologyProperties_(ontology : Ontology)
	# _closeOntology(ontology : Ontology, ontologyMenu : QMenu)
}

