class InfoLog {
  - filename : String
  - socket : String
  - root_logger : logger
  - f_handler : RotatingFileHandler
  - s_handler : SocketHandler
  
  + __init__(loglevel=logging.WARNING : int, filename=default_log_path : String, socket_path : String) : InfoLog
  + set_loglevel(level : int)
}
