class InfoLog {
  - file_name : String
  - last_entry : String
  
  + __init__(loglevel=logging.WARNING : int, filename=default_log_path : String) : InfoLog
  + set_loglevel(level : int)
  + get_log() : String[]
  + get_log_tail(num=10 : int) : String[]
}
