class PluginManager {
 - plugins : (path : String, widget : Widget)[]
 + get_plugins() : Widget[]
 + add_plugin(path : String) : Boolean
 + remove_plugin(name : String) : Boolean
 + show_options()
}

class WSettings {
	+ __init__(widget : Widget) : WSettings
}

class OptionDialog {
  - options : Dictionary
  + createView()
  + save(path : String)
  + load(path : String)
}
