class SyntaxController {
	- actionlog : ActionLog
	- index : IndexAbstractor
	+ __init__(index : IndexAbstractor) : SyntaxController
	+ parse_partial(code_block)
	+ parse_add(code_block)
	+ parse_graph(graph)
	+ add_ontology(ontology)
	+ remove_ontology(ontology)
	+ serialize(ontology, path=None)
}

class Ontology {
	- name : String
	- revision : Float
	- path : String
	- url : String
	- active : Boolean

	+ __init__(path : String, name=None : String, url=None : String) : Ontology
}

SyntaxController --> Ontology : > uses
