# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphWidget.ui'
#
# Created: Thu Mar 19 23:10:53 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(889, 680)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 0, 881, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setMinimum(0.01)
        self.doubleSpinBox.setMaximum(5.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 9, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 12)
        self.rootSelector = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rootSelector.sizePolicy().hasHeightForWidth())
        self.rootSelector.setSizePolicy(sizePolicy)
        self.rootSelector.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.rootSelector.setObjectName("rootSelector")
        self.rootSelector.addItem("")
        self.gridLayout.addWidget(self.rootSelector, 0, 11, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.relations = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relations.sizePolicy().hasHeightForWidth())
        self.relations.setSizePolicy(sizePolicy)
        self.relations.setEditable(True)
        self.relations.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.relations.setObjectName("relations")
        self.relations.addItem("")
        self.relations.addItem("")
        self.relations.addItem("")
        self.gridLayout.addWidget(self.relations, 0, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label2 = QtGui.QLabel(self.layoutWidget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 10, 1, 1)
        self.depth = QtGui.QSpinBox(self.layoutWidget)
        self.depth.setMinimum(-1)
        self.depth.setProperty("value", -1)
        self.depth.setObjectName("depth")
        self.gridLayout.addWidget(self.depth, 0, 7, 1, 1)
        self.activeOntology = QtGui.QComboBox(self.layoutWidget)
        self.activeOntology.setObjectName("activeOntology")
        self.gridLayout.addWidget(self.activeOntology, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.rootSelector.setWhatsThis(QtGui.QApplication.translate("Form", "Root selector", None, QtGui.QApplication.UnicodeUTF8))
        self.rootSelector.setItemText(0, QtGui.QApplication.translate("Form", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Search for node:", None, QtGui.QApplication.UnicodeUTF8))
        self.relations.setItemText(0, QtGui.QApplication.translate("Form", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.relations.setItemText(1, QtGui.QApplication.translate("Form", "instance", None, QtGui.QApplication.UnicodeUTF8))
        self.relations.setItemText(2, QtGui.QApplication.translate("Form", "subclass", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Form", "Select root node", None, QtGui.QApplication.UnicodeUTF8))
        self.depth.setStatusTip(QtGui.QApplication.translate("Form", "-1 for infinity depth", None, QtGui.QApplication.UnicodeUTF8))

