# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionDialog.ui'
#
# Created: Thu Feb 26 15:15:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(679, 540)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/gfx/actions/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtGui.QListWidget(self.widget)
        self.listWidget.setMaximumSize(QtCore.QSize(96, 16777215))
        self.listWidget.setIconSize(QtCore.QSize(64, 64))
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setSpacing(12)
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/gfx/globulation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/gfx/accessories-text-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon2)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/gfx/x-office-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon3)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/gfx/view-sidetree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon4)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/gfx/graphics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon5)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.widget_2 = QtGui.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.configPath = QtGui.QLineEdit(self.widget_2)
        self.configPath.setReadOnly(True)
        self.configPath.setObjectName("configPath")
        self.horizontalLayout_5.addWidget(self.configPath)
        self.configPathChooser = QtGui.QToolButton(self.widget_2)
        self.configPathChooser.setObjectName("configPathChooser")
        self.horizontalLayout_5.addWidget(self.configPathChooser)
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.widget_2)
        self.gridLayout_17.addLayout(self.formLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_10 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.maxQueueSize = QtGui.QSpinBox(self.groupBox_5)
        self.maxQueueSize.setObjectName("maxQueueSize")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxQueueSize)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.maxUndoRedoQueueSize = QtGui.QSpinBox(self.groupBox_5)
        self.maxUndoRedoQueueSize.setObjectName("maxUndoRedoQueueSize")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxUndoRedoQueueSize)
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.flushWriteQueuesTimeout = QtGui.QSpinBox(self.groupBox_5)
        self.flushWriteQueuesTimeout.setObjectName("flushWriteQueuesTimeout")
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.flushWriteQueuesTimeout)
        self.gridLayout_18.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_11 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_11.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setObjectName("label_21")
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.widget_3 = QtGui.QWidget(self.groupBox_6)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logOutputPath = QtGui.QLineEdit(self.widget_3)
        self.logOutputPath.setReadOnly(True)
        self.logOutputPath.setObjectName("logOutputPath")
        self.horizontalLayout_6.addWidget(self.logOutputPath)
        self.logOutputPathChooser = QtGui.QToolButton(self.widget_3)
        self.logOutputPathChooser.setObjectName("logOutputPathChooser")
        self.horizontalLayout_6.addWidget(self.logOutputPathChooser)
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.widget_3)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.widget_4 = QtGui.QWidget(self.groupBox_6)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.socketOutputPath = QtGui.QLineEdit(self.widget_4)
        self.socketOutputPath.setReadOnly(True)
        self.socketOutputPath.setObjectName("socketOutputPath")
        self.horizontalLayout_7.addWidget(self.socketOutputPath)
        self.socketOutputPathChooser = QtGui.QToolButton(self.widget_4)
        self.socketOutputPathChooser.setObjectName("socketOutputPathChooser")
        self.horizontalLayout_7.addWidget(self.socketOutputPathChooser)
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.widget_4)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.logLevel = QtGui.QSpinBox(self.groupBox_6)
        self.logLevel.setObjectName("logLevel")
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.logLevel)
        self.gridLayout_18.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_2 = QtGui.QTabWidget(self.page_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.maxTextEditorWidgets = QtGui.QSpinBox(self.tab_3)
        self.maxTextEditorWidgets.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.maxTextEditorWidgets.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.maxTextEditorWidgets.setMinimum(1)
        self.maxTextEditorWidgets.setMaximum(10)
        self.maxTextEditorWidgets.setObjectName("maxTextEditorWidgets")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxTextEditorWidgets)
        self.defaultFontSize = QtGui.QSpinBox(self.tab_3)
        self.defaultFontSize.setObjectName("defaultFontSize")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.defaultFontSize)
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_29)
        self.defaultFontFamily = QtGui.QFontComboBox(self.tab_3)
        self.defaultFontFamily.setObjectName("defaultFontFamily")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.defaultFontFamily)
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_30)
        self.widget_13 = QtGui.QWidget(self.tab_3)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.defaultFontColor = QtGui.QLineEdit(self.widget_13)
        self.defaultFontColor.setObjectName("defaultFontColor")
        self.horizontalLayout_12.addWidget(self.defaultFontColor)
        self.defaultFontColorChooser = QtGui.QToolButton(self.widget_13)
        self.defaultFontColorChooser.setObjectName("defaultFontColorChooser")
        self.horizontalLayout_12.addWidget(self.defaultFontColorChooser)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_13)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.toolBox = QtGui.QToolBox(self.tab_6)
        self.toolBox.setObjectName("toolBox")
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 509, 278))
        self.page_6.setObjectName("page_6")
        self.gridLayout_9 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setVerticalSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtGui.QLabel(self.page_6)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.keywordsFontFamily = QtGui.QFontComboBox(self.page_6)
        self.keywordsFontFamily.setEditable(False)
        self.keywordsFontFamily.setObjectName("keywordsFontFamily")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.keywordsFontFamily)
        self.label_3 = QtGui.QLabel(self.page_6)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.keywordsFontSize = QtGui.QSpinBox(self.page_6)
        self.keywordsFontSize.setObjectName("keywordsFontSize")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.keywordsFontSize)
        self.label_4 = QtGui.QLabel(self.page_6)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_24 = QtGui.QLabel(self.page_6)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.widget_5 = QtGui.QWidget(self.page_6)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keywordsBoldStyle = QtGui.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.keywordsBoldStyle.setFont(font)
        self.keywordsBoldStyle.setObjectName("keywordsBoldStyle")
        self.horizontalLayout.addWidget(self.keywordsBoldStyle)
        self.keywordsItalicStyle = QtGui.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.keywordsItalicStyle.setFont(font)
        self.keywordsItalicStyle.setObjectName("keywordsItalicStyle")
        self.horizontalLayout.addWidget(self.keywordsItalicStyle)
        self.keywordsUnderlinedStyle = QtGui.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.keywordsUnderlinedStyle.setFont(font)
        self.keywordsUnderlinedStyle.setObjectName("keywordsUnderlinedStyle")
        self.horizontalLayout.addWidget(self.keywordsUnderlinedStyle)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_5)
        self.widget_9 = QtGui.QWidget(self.page_6)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.keywordsFontColor = QtGui.QLineEdit(self.widget_9)
        self.keywordsFontColor.setReadOnly(True)
        self.keywordsFontColor.setObjectName("keywordsFontColor")
        self.horizontalLayout_8.addWidget(self.keywordsFontColor)
        self.keywordsFontColorChooser = QtGui.QToolButton(self.widget_9)
        self.keywordsFontColorChooser.setObjectName("keywordsFontColorChooser")
        self.horizontalLayout_8.addWidget(self.keywordsFontColorChooser)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget_9)
        self.gridLayout_9.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 353, 159))
        self.page_7.setObjectName("page_7")
        self.gridLayout_10 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setVerticalSpacing(12)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtGui.QLabel(self.page_7)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.logicExprFontFamily = QtGui.QFontComboBox(self.page_7)
        self.logicExprFontFamily.setEditable(False)
        self.logicExprFontFamily.setObjectName("logicExprFontFamily")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.logicExprFontFamily)
        self.label_6 = QtGui.QLabel(self.page_7)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.logicExprFontSize = QtGui.QSpinBox(self.page_7)
        self.logicExprFontSize.setObjectName("logicExprFontSize")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.logicExprFontSize)
        self.label_7 = QtGui.QLabel(self.page_7)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_25 = QtGui.QLabel(self.page_7)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_25)
        self.widget_6 = QtGui.QWidget(self.page_7)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logicExprBoldStyle = QtGui.QCheckBox(self.widget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.logicExprBoldStyle.setFont(font)
        self.logicExprBoldStyle.setObjectName("logicExprBoldStyle")
        self.horizontalLayout_2.addWidget(self.logicExprBoldStyle)
        self.logicExprItalicStyle = QtGui.QCheckBox(self.widget_6)
        font = QtGui.QFont()
        font.setItalic(True)
        self.logicExprItalicStyle.setFont(font)
        self.logicExprItalicStyle.setObjectName("logicExprItalicStyle")
        self.horizontalLayout_2.addWidget(self.logicExprItalicStyle)
        self.logicExprUnderlinedStyle = QtGui.QCheckBox(self.widget_6)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.logicExprUnderlinedStyle.setFont(font)
        self.logicExprUnderlinedStyle.setObjectName("logicExprUnderlinedStyle")
        self.horizontalLayout_2.addWidget(self.logicExprUnderlinedStyle)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_6)
        self.widget_10 = QtGui.QWidget(self.page_7)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.logicExprFontColor = QtGui.QLineEdit(self.widget_10)
        self.logicExprFontColor.setObjectName("logicExprFontColor")
        self.horizontalLayout_9.addWidget(self.logicExprFontColor)
        self.logicExprFontColorChooser = QtGui.QToolButton(self.widget_10)
        self.logicExprFontColorChooser.setObjectName("logicExprFontColorChooser")
        self.horizontalLayout_9.addWidget(self.logicExprFontColorChooser)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget_10)
        self.gridLayout_10.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_7, "")
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 353, 159))
        self.page_8.setObjectName("page_8")
        self.gridLayout_11 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setVerticalSpacing(12)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtGui.QLabel(self.page_8)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.commentFontFamily = QtGui.QFontComboBox(self.page_8)
        self.commentFontFamily.setEditable(False)
        self.commentFontFamily.setObjectName("commentFontFamily")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.commentFontFamily)
        self.label_9 = QtGui.QLabel(self.page_8)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.commentFontSize = QtGui.QSpinBox(self.page_8)
        self.commentFontSize.setObjectName("commentFontSize")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.commentFontSize)
        self.label_10 = QtGui.QLabel(self.page_8)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_26 = QtGui.QLabel(self.page_8)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_26)
        self.widget_7 = QtGui.QWidget(self.page_8)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.commentBoldStyle = QtGui.QCheckBox(self.widget_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.commentBoldStyle.setFont(font)
        self.commentBoldStyle.setObjectName("commentBoldStyle")
        self.horizontalLayout_3.addWidget(self.commentBoldStyle)
        self.commentItalicStyle = QtGui.QCheckBox(self.widget_7)
        font = QtGui.QFont()
        font.setItalic(True)
        self.commentItalicStyle.setFont(font)
        self.commentItalicStyle.setObjectName("commentItalicStyle")
        self.horizontalLayout_3.addWidget(self.commentItalicStyle)
        self.commentUnderlinedStyle = QtGui.QCheckBox(self.widget_7)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.commentUnderlinedStyle.setFont(font)
        self.commentUnderlinedStyle.setObjectName("commentUnderlinedStyle")
        self.horizontalLayout_3.addWidget(self.commentUnderlinedStyle)
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_7)
        self.widget_11 = QtGui.QWidget(self.page_8)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.commentFontColor = QtGui.QLineEdit(self.widget_11)
        self.commentFontColor.setObjectName("commentFontColor")
        self.horizontalLayout_10.addWidget(self.commentFontColor)
        self.commentFontColorChooser = QtGui.QToolButton(self.widget_11)
        self.commentFontColorChooser.setObjectName("commentFontColorChooser")
        self.horizontalLayout_10.addWidget(self.commentFontColorChooser)
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget_11)
        self.gridLayout_11.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_8, "")
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 353, 159))
        self.page_9.setObjectName("page_9")
        self.gridLayout_12 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setVerticalSpacing(12)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_11 = QtGui.QLabel(self.page_9)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.stringsFontFamily = QtGui.QFontComboBox(self.page_9)
        self.stringsFontFamily.setEditable(False)
        self.stringsFontFamily.setObjectName("stringsFontFamily")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.stringsFontFamily)
        self.label_12 = QtGui.QLabel(self.page_9)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.stringsFontSize = QtGui.QSpinBox(self.page_9)
        self.stringsFontSize.setObjectName("stringsFontSize")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.stringsFontSize)
        self.label_13 = QtGui.QLabel(self.page_9)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_27 = QtGui.QLabel(self.page_9)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_27)
        self.widget_8 = QtGui.QWidget(self.page_9)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stringsBoldStyle = QtGui.QCheckBox(self.widget_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stringsBoldStyle.setFont(font)
        self.stringsBoldStyle.setObjectName("stringsBoldStyle")
        self.horizontalLayout_4.addWidget(self.stringsBoldStyle)
        self.stringsItalicStyle = QtGui.QCheckBox(self.widget_8)
        font = QtGui.QFont()
        font.setItalic(True)
        self.stringsItalicStyle.setFont(font)
        self.stringsItalicStyle.setObjectName("stringsItalicStyle")
        self.horizontalLayout_4.addWidget(self.stringsItalicStyle)
        self.stringsUnderlinedStyle = QtGui.QCheckBox(self.widget_8)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.stringsUnderlinedStyle.setFont(font)
        self.stringsUnderlinedStyle.setObjectName("stringsUnderlinedStyle")
        self.horizontalLayout_4.addWidget(self.stringsUnderlinedStyle)
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_8)
        self.widget_12 = QtGui.QWidget(self.page_9)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stringsFontColor = QtGui.QLineEdit(self.widget_12)
        self.stringsFontColor.setObjectName("stringsFontColor")
        self.horizontalLayout_11.addWidget(self.stringsFontColor)
        self.stringsFontColorChooser = QtGui.QToolButton(self.widget_12)
        self.stringsFontColorChooser.setObjectName("stringsFontColorChooser")
        self.horizontalLayout_11.addWidget(self.stringsFontColorChooser)
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget_12)
        self.gridLayout_12.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_9, "")
        self.gridLayout_8.addWidget(self.toolBox, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_13 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget_5 = QtGui.QTabWidget(self.page_3)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_14 = QtGui.QLabel(self.tab_7)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.maxDocumentationWidgets = QtGui.QSpinBox(self.tab_7)
        self.maxDocumentationWidgets.setReadOnly(False)
        self.maxDocumentationWidgets.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.maxDocumentationWidgets.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.maxDocumentationWidgets.setMaximum(10)
        self.maxDocumentationWidgets.setObjectName("maxDocumentationWidgets")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxDocumentationWidgets)
        self.gridLayout_14.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_7, "")
        self.gridLayout_13.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_3 = QtGui.QTabWidget(self.page_4)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.maxHierarchyWidgets = QtGui.QSpinBox(self.tab_4)
        self.maxHierarchyWidgets.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.maxHierarchyWidgets.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.maxHierarchyWidgets.setMaximum(10)
        self.maxHierarchyWidgets.setObjectName("maxHierarchyWidgets")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxHierarchyWidgets)
        self.gridLayout_15.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_4 = QtGui.QTabWidget(self.page_5)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.maxGraphWidgets = QtGui.QSpinBox(self.tab_5)
        self.maxGraphWidgets.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.maxGraphWidgets.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.maxGraphWidgets.setMaximum(10)
        self.maxGraphWidgets.setProperty("value", 1)
        self.maxGraphWidgets.setObjectName("maxGraphWidgets")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxGraphWidgets)
        self.gridLayout_16.addLayout(self.formLayout_8, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_5, "")
        self.gridLayout_6.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.listWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), Dialog.changePage)
        QtCore.QObject.connect(self.stackedWidget, QtCore.SIGNAL("currentChanged(int)"), Dialog.setSelectedPage)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Default Output Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.configPathChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Misc.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Action Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Max. Write Queue Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Max. Undo/Redo Queue Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Flush Write Queues Timeout: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Info Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Log Output Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.logOutputPathChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Socket Output Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.socketOutputPathChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Log Level: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("Dialog", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Max. Number of Text Editor Widgets: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "Default Font Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Default Font Family: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog", "Default Font Color: ", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFontColorChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Misc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Font Family: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Font Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Text Color: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Font Style: ", None, QtGui.QApplication.UnicodeUTF8))
        self.keywordsBoldStyle.setText(QtGui.QApplication.translate("Dialog", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.keywordsItalicStyle.setText(QtGui.QApplication.translate("Dialog", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.keywordsUnderlinedStyle.setText(QtGui.QApplication.translate("Dialog", "Underlined", None, QtGui.QApplication.UnicodeUTF8))
        self.keywordsFontColorChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), QtGui.QApplication.translate("Dialog", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Font Family: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Font Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Text Color: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Font Style: ", None, QtGui.QApplication.UnicodeUTF8))
        self.logicExprBoldStyle.setText(QtGui.QApplication.translate("Dialog", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.logicExprItalicStyle.setText(QtGui.QApplication.translate("Dialog", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.logicExprUnderlinedStyle.setText(QtGui.QApplication.translate("Dialog", "Underlined", None, QtGui.QApplication.UnicodeUTF8))
        self.logicExprFontColorChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), QtGui.QApplication.translate("Dialog", "Logic Expressions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Font Family: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Font Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Text Color: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Font Style: ", None, QtGui.QApplication.UnicodeUTF8))
        self.commentBoldStyle.setText(QtGui.QApplication.translate("Dialog", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.commentItalicStyle.setText(QtGui.QApplication.translate("Dialog", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.commentUnderlinedStyle.setText(QtGui.QApplication.translate("Dialog", "Underlined", None, QtGui.QApplication.UnicodeUTF8))
        self.commentFontColorChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), QtGui.QApplication.translate("Dialog", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Font Family: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Font Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Text Color: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Font Style: ", None, QtGui.QApplication.UnicodeUTF8))
        self.stringsBoldStyle.setText(QtGui.QApplication.translate("Dialog", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.stringsItalicStyle.setText(QtGui.QApplication.translate("Dialog", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.stringsUnderlinedStyle.setText(QtGui.QApplication.translate("Dialog", "Underlined", None, QtGui.QApplication.UnicodeUTF8))
        self.stringsFontColorChooser.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), QtGui.QApplication.translate("Dialog", "Strings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Syntax Highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Max. Number of Documentation Widgets: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_7), QtGui.QApplication.translate("Dialog", "Misc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Max. Number of Hierarchy Widgets: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Misc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Max. Number of Graph Widgets: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Misc.", None, QtGui.QApplication.UnicodeUTF8))

import pySUMOQt.Designer.gfx_rc
